### ISSUE TITLE
some problems with deployment in heroku

### ISSUE THREAD

**Issue by subhrapaladhi** [CodeChefVIT/getting-started#2]
[Reaseach paper query](https://research-paper-query-cc.herokuapp.com/)
I have deployed my web app in the above link.

After the website is idle for long hours and then if someone uses the app and clicks on the download button it doesn't work. By looking into logs I figured out that cheerio is receiving the HTML from the sci-hub but it was unable to scrape the download link from it. 

Moreover, I noticed that if manually refresh the dynos from my Heroku account that the web app starts working fine again.

Can someone explain what is causing this problem and what will be the approach to the solution?

**Comment by L04DB4L4NC3R** [comment]
If someone uses the application and even reaches the front page then the dynos get restarted

**Comment by L04DB4L4NC3R** [comment]
Don't send any requests for half an hour. I will try to recreate this problem at 4 pm

**Comment by subhrapaladhi** [comment]
@L04DB4L4NC3R Ok

**Comment by L04DB4L4NC3R** [comment]
@subhrapaladhi  Its working

**Comment by subhrapaladhi** [comment]
@L04DB4L4NC3R 
okay
if doesn't work then i will tell you..

**Comment by L04DB4L4NC3R** [comment]
@subhrapaladhi Create an issue in your repo the next time

**Comment by subhrapaladhi** [comment]
ok
